// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzSCj-cWwqSWPV6VDEsEXYco0PFjNDIn8',
    appId: '1:138278663781:web:cb66d5d2e883e4e209388c',
    messagingSenderId: '138278663781',
    projectId: 'cipherx-expense-app',
    authDomain: 'cipherx-expense-app.firebaseapp.com',
    storageBucket: 'cipherx-expense-app.firebasestorage.app',
    measurementId: 'G-FV1155VYG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzTamj54i2RlzmswIjGcXfbO1qySAZ9FM',
    appId: '1:138278663781:android:bdc747506d00a1fb09388c',
    messagingSenderId: '138278663781',
    projectId: 'cipherx-expense-app',
    storageBucket: 'cipherx-expense-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNyyQu5_skpTLJTuEsLqPoBYegGNyyRss',
    appId: '1:138278663781:ios:ca1a3e380b9c126a09388c',
    messagingSenderId: '138278663781',
    projectId: 'cipherx-expense-app',
    storageBucket: 'cipherx-expense-app.firebasestorage.app',
    androidClientId: '138278663781-9sq0ag3urqi9puhdu69ooq2me4jk3vhg.apps.googleusercontent.com',
    iosClientId: '138278663781-c5emb9j0kjnhauh2ruokn85a4livghgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipherschoolsFlutterAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzSCj-cWwqSWPV6VDEsEXYco0PFjNDIn8',
    appId: '1:138278663781:web:cc401df5f05eda0d09388c',
    messagingSenderId: '138278663781',
    projectId: 'cipherx-expense-app',
    authDomain: 'cipherx-expense-app.firebaseapp.com',
    storageBucket: 'cipherx-expense-app.firebasestorage.app',
    measurementId: 'G-95FS928N41',
  );
}
